### ISSUE TITLE
README pictures

### ISSUE THREAD

**Issue by rubenafo** [rubenafo/svgart#1]
![shapenode](https://cloud.githubusercontent.com/assets/1132995/12775077/133e637e-ca43-11e5-87ad-5d1fbc33b50f.png)
![svgnode](https://cloud.githubusercontent.com/assets/1132995/12775075/1324a2c2-ca43-11e5-905f-9c7a5ab5bec4.png)
![toolbar](https://cloud.githubusercontent.com/assets/1132995/12775076/132a5faa-ca43-11e5-9cdf-a7d100bfdd24.png)

**Comment by figurebelow** [comment]
This issue just uploads the files to be displayed in the wiki/ Readme.md
